language: node_js
node_js: 
    - '11'
install:
  - npm install
after_script:
  - cd ./dist
  - git init
  - git config user.name "wuxiwe"
  - git config user.email "2509165479@qq.com"
  - git add -A
  - git commit -m "Update documents"
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" "master:gh-pages"
branches:
  only:
    - master