language: node_js
node_js: 
    - '11'
cache:
  directories:
    - node_modules
install:
  - npm install
after_script:
  - cd ./dist
  - git init
  - git config user.name "wuxiwe"
  - git config user.email "2509165479@qq.com"
  - git add .
  - git commit -m "react project"
  - git push --force --quiet  "https://${GH_TOKEN}@github.com/wuxuweilalala/react-ts-template.git" "master:gh-pages"